import '../../../styles/globals.css';
import { Open_Sans } from 'next/font/google';
import Header from '../components/homeAuth/Header/Header';

const openSans = Open_Sans({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className={openSans.className}>{children}</main>
      </body>
    </html>
  );
}
